name: Build and Deploy Application

on:
  push:
    branches:
      - ufo
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: sample message
      run: | 
        echo "Hello World from prod env"
