name: Build and Deploy Application

on:
  push:
    branches:
      - dev-docker
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
